  // {
  //   hexArray: [0x04, 0x04, 0x01, 0xAA],
  //   preIndexs: 0,
  //   indexs: 0,
  //   lastedBtn: '0',
  //   status: 0,
  //   jsonDataAlive: {},
  //   jsonDataCount: {},
  // },
  // {
  //   hexArray: [0x04, 0x04, 0x01, 0xAA],
  //   preIndexs: 0,
  //   indexs: 0,
  //   lastedBtn: '0',
  //   status: 0,
  //   jsonDataAlive: {},
  //   jsonDataCount: {},
  // },